name: Publish to DockerHub

on:
  push:
    branches:
      - "master"

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/toumoro-slack-messaging
  API_KEY: ${{ secrets.API_KEY }}
  API_URL: ${{ secrets.API_URL }

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Publish Toumoro Slack Messaging
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          registry: ${{ env.DOCKER_REGISTRY }}
          cache_froms: ${{ env.IMAGE_NAME }}:latest
          repository: ${{ env.IMAGE_NAME }}
          tags: latest
      - name: Deploy Denied
        if: success()
        uses: docker://kerberosmorphy/toumoro-slack-messaging:latest
        with:
          api_url: ${{ env.API_URL }}
          api_key: ${{ env.API_KEY }}
          service: "github"
          project: "Toumoro Slack Messaging"
          channel: "ci-cd"
          ref: ${{ github.ref }}
          run_id: ${{ github.run_id }}
          step: "Deploy"
          type: "status"
          status: "Build:PASS"
          issue_id: "5476"
          actor: ${{ github.actor }}
          repository: ${{ github.repository }}
      - name: Deploy Failure Handler
        if: failure()
        uses: docker://kerberosmorphy/toumoro-slack-messaging:latest
        with:
          api_url: ${{ env.API_URL }}
          api_key: ${{ env.API_KEY }}
          service: "github"
          project: "Toumoro Slack Messaging"
          channel: "ci-cd"
          ref: ${{ github.ref }}
          run_id: ${{ github.run_id }}
          step: "Deploy"
          type: "error"
          status: "Build:FAIL"
          issue_id: "5476"
          actor: ${{ github.actor }}
          repository: ${{ github.repository }}
